### ISSUE TITLE
Format for co-working spaces

### ISSUE THREAD

**Issue by anbraten** [coworkingspaces/spaces#1]
We need to decide on a first version of how we want to store the co-working spaces metadata.

# One file vs one file per space (maybe even folders for countries, states, cities)?

- one file per space could be nice as it would allow us to skip spaces with wrong properties
- issue could be to many files in a folder error
- Question: How do the two options behave in reviews

# Which file format (yaml / json / ...)?

.yml seems pretty easy to write

# Which properties should we add per space for the first version?

## Version 1
- name
- key / id (string like `de-kiel-fleet7`)
- links (array)
  - name (exp booking system, Instagram)
  - url
- description
- email
- phone
- address (as string)
- location
  - lat
  - lon
- images (array)
  - url
  - alt text 

## Version 2
- opening_hours TBD
- prices TBD

**Comment by mariusheine** [comment]
@anbraten I would stay with one file for now due to simplicity, as in my opinion it is the easiest to read for humans. 

I also would prefer json because for me yaml is confusing 🙈 . Nevertheless yml would be fine for me as well 😉 

I totally agree with all your properties except prices and opening hours. I think most of them do not have fixed opening hours and prices might be pretty complex and flacky. For adresses I would keep it as simple as in bookyp: a single string.

**Comment by lukashass** [comment]
JSON has better schema support, but doesn't really matter :shrug: 

For opening hours: https://wiki.openstreetmap.org/wiki/Key:opening_hours/specification

**Comment by anbraten** [comment]
> JSON has better schema support, but doesn't really matter shrug

Works pretty fine with yml as well. See woodpecker config files for example.

> For opening hours: https://wiki.openstreetmap.org/wiki/Key:opening_hours/specification

Nice suggestion. I would also be fine with leaving the prices and opening_hours out for now. Just got that idea from the co-working spaces orgs repo / metadata list.

**Comment by mariusheine** [comment]
We just need telephone number and email adress as additional attributes

**Comment by anbraten** [comment]
@mariusheine just added those properties

**Comment by mariusheine** [comment]
@anbraten Great thx a lot. I showed everything to ellen and she wanted to write it down in JSON for now.

**Comment by ellenheine** [comment]
@anbraten I also added logo with url as a property.

**Comment by mariusheine** [comment]
@anbraten I think our format is fine for now so let's close this issue and see what additional properties are necessary in the future?
